### ISSUE TITLE
understanding feature projection and .mat file

### ISSUE THREAD

**Issue by NguyenTriTrinh** [yuxiaoguo/VVNet#9]
Hi, 
In the 3.2 feature projection part ,compared with SSCNet ,you replaced the TSDF with feature projection right? when depth map passed by 2D view network,there was a pooling operation, after that, several neighboring features were projected into the same voxel in the projection , so there were two pooling operations in total? You used the feature maps constructed by the 2D view network as the input to the projection instead of the original depth map, am i right?
Another question,when i load the `XXXX_gt_d4.mat `and `XXXX_vol_d4.mat`, i get `distance_ds`,`flipVol_ds`,`sceneVox_ds`,what  are they respectively mean? it seems to me that `distance_ds`represents the tsdf values, and `flipVol_ds`represents the ftsdf values.

**Comment by yuxiaoguo** [comment]
Sorry for the late response. 

About the feature projection, your understanding is totally right. During the projection, many pixels may fall into an identity voxel. Thus, an average pooling operation is imported to handle this case.

About the content in MAT files, I don't fully understand the content as well. Fortunately, we just need to derive the surface and non-surface information. For this propose, you may refer to the [analysis/statistics.py](https://github.com/yuxiaoguo/VVNet/blob/master/analysis/statistics.py). For other proposes, ask the SSCNet author may a better choice.

**Comment by NguyenTriTrinh** [comment]
thank u for your reply! i have already understood.
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yuxiaoguo"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 下午2:23
收件人: "yuxiaoguo/VVNet"<VVNet@noreply.github.com&gt;; 
抄送: "雤 ﹊踜|〆.."<644538318@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [yuxiaoguo/VVNet] understanding feature projection and .mat file (#9)




Sorry for the late response.
 
About the feature projection, your understanding is totally right. During the projection, many pixels may fall into an identity voxel. Thus, an average pooling operation is imported to handle this case.
 
About the content in MAT files, I don't fully understand the content as well. Fortunately, we just need to derive the surface and non-surface information. For this propose, you may refer to the analysis/statistics.py. For other proposes, ask the SSCNet author may a better choice.

**Comment by jiunyen-ching** [comment]
Hi @yuxiaoguo sorry to hijack the conversation.

In _statistics.py_, you have SEG_36_11 with 37 elements in the array.  When I print the array slices (i.e. 240x144x1, 240x144x2 ... 240x144x240), I noticed that there are voxels with the values of 0 - 36 and 255.

Is this value (255) representing voxels that are out of field of view?
